### PR TITLE
Fileprovider.Watch("") Does not work as expected Issue#21

### PR DESCRIPTION
**Pull request by RPaetau**
What i ended up doing was simply adding */* to watch filter and added some tests to see that it works how i expect and i dident break anything unintentionally

### CODE REVIEW

**Comment by dazinator** [comment]
It looks like the build is failing now due to VS updates.
I will fix this in the dev branch and then you can merge dev (or rebase I dont mind) and hopefully this build will turn green

**Comment by RPaetau** [comment]
Thanks thats great (: Ill just merge dev (:

**Comment by dazinator** [comment]
Ok - develop branch is building again please merge!
I have made a few changes, like updating xunit, and dotnet.glob dependencies, and updaitng the csproj files to remove some obsolete stuff.
The biggest change was I switched the tests to run on `netcoreapp2.0`.

**Comment by RPaetau** [comment]
The changes dident affect the changes ive made, so i think its all good now (:

**Comment by dazinator** [comment]
LGTM!

**Comment by RPaetau** [comment]
I dident consider that scenario.. 
I tried just appending "/*" but it dident work. 
It was something with the root folder actually being a folder with a name, so it got confused when trying to compare root/test.txt to "/*" cause root is there, i dont remember exactly where this issue was, but i think it was when trying to figure out if any filters matched an add change

**Comment by dazinator** [comment]
Ok thats no problem. We have more passing tests now (thanks), so that's why I was happy to merge. Its now a case of extending the tests to cover this more thoroughly.

At the moment I am thinking the end result might be something like this:

1. Watch for any changes within `/foo` folder = `Watch("foo/*")
2. Watch for any changes within folders starting with "/foo" = `Watch("foo*/*")
3. Watch for any changes within folders or any subfolders starting with "/foo" = `Watch("foo*/**/*")

At the moment what this PR does, is work out if the pattern passed in is just a directory pattern - and if it is, it assumes you want to watch for changes in that directory and so it extends the pattern.

However you could pass in `/foo/*` and it would append `*/*` so the pattern would end up being `/foo/**/*` - which means match files in any subfolder of `foo`. This is probably a bug :-)

**Comment by dazinator** [comment]
I'll open an issue to add more test coverage for this

**Pull request merged**
